import { getFormDataFromState } from '../src/features/test-data/buildTestDataDocument.js'
import type { TestDataFormMap } from '../src/features/test-data/buildTestDataDocument.js'
import { defaultStateMachineReason } from '../src/shared/constants/stateMachineReason.js'

export function buildCliFormData(count: number, mode: 'acs' | 'dss' = 'acs'): TestDataFormMap {
  const now = new Date()
  const currentDate = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`

  return getFormDataFromState({
    batchSize: String(count),
    batchDays: '0',
    mode,
    currentDate,
    enableCustomTimeRange: false,
    enableAutoTimeRange: false,
    timezone: 'browser',
    issuerOid: '06b4b203-da05-73f9-256f-454929df6076',
    requestorId: '12128301823081230123',
    acsTransId: '',
    threeDSServerTransId: '',
    aresTransStatus: 'N',
    transStatus: 'N',
    rreqTransStatus: 'NULL_VALUE',
    transStatusReason: 'NULL_VALUE',
    stateMachineReason: defaultStateMachineReason(mode),
    transStatusReasonMode: 'random',
    stateMachineReasonMode: 'random',
    challengeCancel: 'NULL_VALUE',
    aresWeightY: '6',
    aresWeightN: '4',
    aresWeightR: '3',
    aresWeightC: '84',
    aresWeightD: '0',
    aresWeightA: '0',
    aresWeightI: '1',
    aresWeightS: '0',
    aresWeightU: '2',
    rreqWeightNull: '5',
    rreqWeightY: '86',
    rreqWeightN: '9',
    challengeCancelRate: '8',
    merchantName: 'HiTRUST EMV Demo Merchant',
    merchantCountryCode: '156',
    acquirerMerchantId: '8909191',
    acquirerBin: '1231234',
    mcc: '5661',
    purchaseAmount: '100',
    purchaseCurrency: '156',
    purchaseExponent: '2',
    countryNumeric: '156',
    cardScheme: 'V',
    acctNumber: '4143520000000123',
    cardbin6: '414352',
    messageCategory: '01',
    messageVersion: '2.2.0',
    deviceChannel: '02',
    threeDSRequestorChallengeInd: '01',
    authenticationMethod: '02',
    authenticationType: '02',
    deviceIpAddress: '::1',
    browserIP: '::1',
    devicePlatform: 'MacIntel',
    deviceLocale: 'zh-TW',
    threeDSCompInd: 'Y',
    merchantCountryCodeStr: '156',
    performancePath: '/acs-auth/auth/V/2.2.0/06b4b203-da05-73f9-256f-454929df6076/001/areq',
    execTime: '5437',
    creqExecTime: '500',
    rreqExecTime: '400',
    rbaExecTime: '100',
    cavvExecTime: '20',
    otpExecTime: '50',
    errorComponent: 'NULL_VALUE',
    errorDescription: 'NULL_VALUE',
    errorCode: 'NULL_VALUE',
    errorDetail: 'NULL_VALUE',
    errorMessageType: 'NULL_VALUE',
    enableBatchErrorMix: true,
    batchErrorMixPercent: '15',
    enablePurchaseAmountRandom: true,
    enableCardSchemeRandom: true,
    enableAcctNumberRandom: true,
    enableAcquirerMerchantIdRandom: true,
    enableAcquirerBinRandom: true,
    enableMerchantRandom: true,
    enablePurchaseCurrencyRandom: true,
    enableMerchantCountryCodeRandom: true,
    enableMerchantCountryAsiaOnly: true,
    enableExecTimeRandom: true,
    enableCreqExecTimeRandom: true,
    enableRreqExecTimeRandom: true,
    enableRbaExecTimeRandom: true,
    enableCavvExecTimeRandom: true,
    enableOtpExecTimeRandom: true,
    enableAll3DSParamsRandom: true,
    enableMessageCategory: true,
    enableDeviceChannel: true,
    enableThreeDSRequestorChallengeInd: true,
    enableDeviceIpAddressRandom: true,
    enableDevicePlatformRandom: true,
    enableDeviceLocaleRandom: true,
    enableDeviceAdvertisingIdRandom: true,
    enableThreeDSCompIndRandom: true,
    enableAuthenticationMethodRandom: true,
    enableAuthenticationTypeRandom: true,
    enableBrowserGeoIPRandom: true,
    enableDeviceGeoIPRandom: true,
    disableRreqTransStatus: true,
    disableTransStatusReason: true,
    disableStateMachineReason: true,
    disableChallengeCancel: true
  })
}
